### ISSUE TITLE
Added Review Scrapper

### ISSUE THREAD

**Issue by Vaibhav832** [aarushiksk/Noob-to-Ninja-ML#14]
This data science project uses Python to scrape reviews from Flipkart, an Indian e-commerce platform. The project has two main goals:

1. To collect data on customer satisfaction with Flipkart products and services.

2. To use this data to identify areas where Flipkart could improve its offerings.

**Comment by aarushiksk** [comment]
Hi I see you want to add a review scrapper project, do you maybe want to provide a description of what your project is about?

**Comment by Vaibhav832** [comment]
Done
