### ISSUE TITLE
Added Youtube Scrapper

### ISSUE THREAD

**Issue by Vaibhav832** [aarushiksk/Noob-to-Ninja-ML#19]
My YouTube Scraper Data Science Project is a fascinating endeavor that leverages the power of the Selenium Python library. This project involves writing a script to scrape data from YouTube. The data collected can include video titles, descriptions, number of views, and more. The use of Selenium allows for dynamic web scraping, which is crucial given YouTube’s JavaScript-based structure.

**Comment by aarushiksk** [comment]
Hi! I see that you've already contributed to my repo, I am adding this project of yours but do keep in mind that you have to **contribute to 4 different repositories for hacktoberfest** so do consider adding your projects to a different repos.
