### ISSUE TITLE
Create a basic RAG system

### ISSUE THREAD

**Issue by Tanish2207** [aarushiksk/Noob-to-Ninja-ML#27]
# Description
Create a basic text-based RAG (Retrieval-Augmented Generation) system .

## RAG
*Retrieval-Augmented Generation (RAG)* is a hybrid approach that combines retrieval and generation techniques in natural language processing. It retrieves relevant documents or information from a knowledge base or corpus and then feeds this information into a language model to generate a response. RAG improves the accuracy and relevance of responses by grounding them in retrieved context rather than relying solely on the model's learned knowledge. It's especially useful for tasks requiring specific, up-to-date information, such as question answering or summarization.

## User Workflow:
- User will provide a .txt file to the agent
- He/she will ask a query 
- The answer to the query should be retrieved from the provided document (or if cannot retrieve, then a message explaining that 'context cannot be retrieved' should be displayed.
- The retrieved context would be passed to a LLM which will frame the answer to the query and the display it.

**Comment by aarushiksk** [comment]
Hey, the RAG chatbot has been merged!!
