### ISSUE TITLE
Create a UI for number guessing game using Streamlit

### ISSUE THREAD

**Issue by aarushiksk** [aarushiksk/Noob-to-Ninja-ML#6]
Create a nice interactive UI design using StreamLit and deploy the app if feasible.

**Comment by Athena-2003** [comment]
I can try. If you can assign me this problem.

**Comment by aarushiksk** [comment]
Hey! I see that you've already contributed one of your projects to this repo, having 2 contributions in one single repo might get your contribution rejected by HacktoberFest team. Therefore, I suggest you try some other repositories. If you need help in finding some I can help you for sure.

**Comment by Athena-2003** [comment]
Ohh. Really ? If you know some repos any help is appreciated.

**Comment by aarushiksk** [comment]
https://github.com/rudra016/WebDev-OpenSource   

Here's a link to a front-end repo!

**Comment by Athena-2003** [comment]
Thank you. Really appreciate it

**Comment by Athena-2003** [comment]
And i have already done part of the streamlit thing. Is it ok if i contribute ?

**Comment by aarushiksk** [comment]
No, I am sorry, what's the use of contributing if it doesn't count right? We aim at providing a smooth HacktoberFest event experience :)

**Comment by Athena-2003** [comment]
OK. But fyi: multiple PR to the same repo does count. Anyways appreciate your help. Have fun contributing.

**Comment by aarushiksk** [comment]
Why take risks right :) fyi, you can also join hacktoberfest discord server to find repos as well!

**Comment by Athena-2003** [comment]
Ohh. Did not know that. Cool. Will check that out. Thanks for everything

**Comment by stanleyedward** [comment]
HEy can i be assigned to this
